#!/usr/bin/env python
# -*- encoding: utf-8 -*-
'''
@Description:TKM_GUI
@Date       :2022/01/28 13:54:54
@Author     :JohnserfSeed
@version    :v2.1.1-alpha
@License    :(C)Copyright 2019-2022, Liugroup-NLPR-CASIA
@Mail       :johnserfseed@gmail.com
'''
# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import Qt, QPoint
from PyQt5.QtGui import QMouseEvent
import resource,sys

class Ui_Dialog(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)

    def setupUi(self, Dialog):
        Dialog.setObjectName("TikTokDownload")
        Dialog.resize(900, 600)
        Dialog.setStyleSheet("")
        self.Label_Left = QtWidgets.QLabel(Dialog)
        self.Label_Left.setGeometry(QtCore.QRect(0, 0, 230, 600))
        self.Label_Left.setStyleSheet("background-color: #060716;\n"
"border-bottom-left-radius: 25px;\n"
"border-top-left-radius: 25px;\n"
"font: 10pt \"微软雅黑\";\n"
"color: #FFFFFF;")
        self.Label_Left.setText("")
        self.Label_Left.setObjectName("Label_Left")
        self.Label_Right = QtWidgets.QLabel(Dialog)
        self.Label_Right.setGeometry(QtCore.QRect(230, 0, 670, 600))
        self.Label_Right.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius: 25px;\n"
"border-bottom-right-radius: 25px;")
        self.Label_Right.setText("")
        self.Label_Right.setObjectName("Label_Right")
        self.Label_Logo = QtWidgets.QLabel(Dialog)
        self.Label_Logo.setGeometry(QtCore.QRect(30, 50, 161, 41))
        self.Label_Logo.setStyleSheet("background: url(:/img/logo-horizontal.svg) no-repeat;")
        self.Label_Logo.setText("")
        self.Label_Logo.setObjectName("Label_Logo")
        self.Label_Version = QtWidgets.QLabel(Dialog)
        self.Label_Version.setGeometry(QtCore.QRect(180, 90, 54, 12))
        self.Label_Version.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 9pt \"華康布丁體\";")
        self.Label_Version.setObjectName("Label_Version")
        self.Button_Close = QtWidgets.QPushButton(Dialog)
        self.Button_Close.setGeometry(QtCore.QRect(860, 20, 21, 21))
        self.Button_Close.setStyleSheet("border-radius: 10px;\n"
"background-color: rgb(255, 81, 53);")
        self.Button_Close.setText("")
        self.Button_Close.setObjectName("Button_Close")
        self.Button_Max = QtWidgets.QPushButton(Dialog)
        self.Button_Max.setGeometry(QtCore.QRect(830, 20, 21, 21))
        self.Button_Max.setStyleSheet("border-radius: 10px;\n"
"background-color: #FFC32D;")
        self.Button_Max.setText("")
        self.Button_Max.setObjectName("Button_Max")
        self.Button_Min = QtWidgets.QPushButton(Dialog)
        self.Button_Min.setGeometry(QtCore.QRect(800, 20, 21, 21))
        self.Button_Min.setStyleSheet("border-radius: 10px;\n"
"background-color: #37C847;")
        self.Button_Min.setText("")
        self.Button_Min.setObjectName("Button_Min")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(260, 100, 471, 41))
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet("background-color: #292B35;\n"
"border-radius: 10px;\n"
"font: 20pt \"華康布丁體\";\n"
"color: rgb(255, 255, 255);")
        self.plainTextEdit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.plainTextEdit.setLineWrapMode(QtWidgets.QPlainTextEdit.WidgetWidth)
        self.plainTextEdit.setBackgroundVisible(False)
        self.plainTextEdit.setCenterOnScroll(False)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.Button_Go = QtWidgets.QPushButton(Dialog)
        self.Button_Go.setGeometry(QtCore.QRect(750, 100, 121, 41))
        self.Button_Go.setStyleSheet("#Button_Go {\n"
"    border-radius: 10px;\n"
"    font: 19pt \"華康布丁體\";\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: #B9BAC7;\n"
"}\n"
"\n"
"#Button_Go:hover {\n"
"    color:#F72C51;\n"
"}\n"
"\n"
"#Button_Go:pressed, QPushButton:checked {\n"
"    background-color: #9d9d9d;\n"
"}\n"
"")
        self.Button_Go.setObjectName("Button_Go")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(230, 0, 670, 60))
        self.label.setStyleSheet("background-color: rgb(199, 199, 199);\n"
"border-top-right-radius: 25px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(260, 190, 611, 351))
        self.widget.setObjectName("widget")
        self.checkBox = QtWidgets.QCheckBox(Dialog)
        self.checkBox.setGeometry(QtCore.QRect(260, 160, 71, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(50, 390, 131, 61))
        self.pushButton.setStyleSheet("border-radius: 25px;\n"
"font: 16pt \"華康布丁體\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(22, 23, 34);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(50, 490, 131, 61))
        self.pushButton_2.setStyleSheet("border-radius: 25px;\n"
"font: 16pt \"華康布丁體\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(22, 23, 34);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.checkBox_2 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_2.setGeometry(QtCore.QRect(340, 160, 101, 16))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(Dialog)
        self.checkBox_3.setGeometry(QtCore.QRect(440, 160, 101, 16))
        self.checkBox_3.setObjectName("checkBox_3")
        self.Label_Right.raise_()
        self.label.raise_()
        self.Label_Left.raise_()
        self.Label_Logo.raise_()
        self.Label_Version.raise_()
        self.Button_Close.raise_()
        self.Button_Max.raise_()
        self.Button_Min.raise_()
        self.plainTextEdit.raise_()
        self.Button_Go.raise_()
        self.widget.raise_()
        self.checkBox.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.checkBox_2.raise_()
        self.checkBox_3.raise_()
        self.setMinimumHeight(600)
        self.setMinimumWidth(900)
        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def mouseMoveEvent(self, e: QMouseEvent):  # 重写移动事件
        try:
            self._endPos = e.pos() - self._startPos
            self.move(self.pos() + self._endPos)
        except:
            pass

    def mousePressEvent(self, e: QMouseEvent):
        try:
            if e.button() == Qt.LeftButton:
                self._isTracking = True
                self._startPos = QPoint(e.x(), e.y())
        except:
            pass

    def mouseReleaseEvent(self, e: QMouseEvent):
        try:
            if e.button() == Qt.LeftButton:
                self._isTracking = False
                self._startPos = None
                self._endPos = None
        except:
            pass

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("TikTokDownload", "TikTokDownload"))
        self.Label_Version.setText(_translate("TikTokDownload", "v2.1.1"))
        self.Button_Min.setToolTip('最小化')
        self.Button_Max.setToolTip('最大化')
        self.Button_Close.setToolTip('关闭')
        self.Button_Go.setText(_translate("TikTokDownload", "咻咻"))
        self.checkBox.setText(_translate("TikTokDownload", "全部下载"))
        self.pushButton.setText(_translate("TikTokDownload", "设置"))
        self.pushButton_2.setText(_translate("TikTokDownload", "关于"))
        self.checkBox_2.setText(_translate("TikTokDownload", "全部封面下载"))
        self.checkBox_3.setText(_translate("TikTokDownload", "全部配乐下载"))
        self.plainTextEdit.setPlainText("https://v.douyin.com")
        self.Button_Max.clicked.connect(lambda: self.MaxButton())
        self.Button_Min.clicked.connect(lambda: self.MinButton())
        self.Button_Close.clicked.connect(lambda: self.CloseButton())

    # 最大化与还原的切换
    def MaxButton(self):
        if self.isMaximized():
            self.showNormal()
            self.Button_Max.setToolTip('最大化')
        else:
            self.showMaximized()
            self.Button_Max.setToolTip('还原')

    # 切换到最小化按钮
    def MinButton(self):
        self.showMinimized()

    # 关闭
    def CloseButton(self):
        sys.exit(0)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = Ui_Dialog()
    # 去掉窗口标题栏和按钮
    w.setWindowFlags(Qt.FramelessWindowHint)
    # 设置窗口真透明
    w.setAttribute(Qt.WA_TranslucentBackground)
    w.show()
    sys.exit(app.exec_())